name: keep_notes
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  font_awesome_flutter: 9.0.0
  curved_navigation_bar: 0.3.7
  google_sign_in: 5.0.1
  cloud_firestore: 1.0.3
  firebase_auth: 1.0.2
  firebase_core: 1.0.3
  cupertino_icons: ^1.0.0
  intl: 0.17.0
  flutter_staggered_grid_view: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
